name: book_Verse
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

#----------------packages----------------#

dependencies:
  flutter:
    sdk: flutter

# Utility packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.3.0
  lottie: ^3.1.2
  connectivity_plus: ^5.0.1
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.3
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  provider: ^6.1.2



#navigation curve menu_bar
  scroll_to_hide_bottom_navigation_bar: ^0.0.1

  # Icons
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

# State Management
  get: ^4.6.6
  get_storage: ^2.1.1

# FireBase
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  google_sign_in: ^6.2.1
  firebase_storage: ^12.1.0
  cached_network_image: ^3.3.1
  cloud_functions: ^5.0.3
  file_picker: ^8.0.6
  parallax: ^1.0.3


# Product Specifier

#------------- ./Packages End -------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
#-----------Local Assets----------#
  assets:
    - assets/
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/animation/
    - assets/images/animation/lottie/
    - assets/icons/icon_genre/
    - assets/icons/category/
    - assets/images/banner/

#----------Local Fonts-----------#
