// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0tKaXVtfzlzeUHtdKukKIh8Doo3c1Wag',
    appId: '1:808424067899:web:c6c869e4e3408a23079d1e',
    messagingSenderId: '808424067899',
    projectId: 'bookverse-8ac90',
    authDomain: 'bookverse-8ac90.firebaseapp.com',
    storageBucket: 'bookverse-8ac90.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl5GNguOJoEOFAcIzIt6PeccN5nDkLXCM',
    appId: '1:808424067899:android:c5178a71fac76328079d1e',
    messagingSenderId: '808424067899',
    projectId: 'bookverse-8ac90',
    storageBucket: 'bookverse-8ac90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-oOIWy_ZznXjeXQGZ7ByT4mOHGyeqgC4',
    appId: '1:808424067899:ios:a099213ab38bb90e079d1e',
    messagingSenderId: '808424067899',
    projectId: 'bookverse-8ac90',
    storageBucket: 'bookverse-8ac90.appspot.com',
    androidClientId: '808424067899-k8h5tg2rroov2srnmmo214uci1v28lml.apps.googleusercontent.com',
    iosClientId: '808424067899-i9h64cektcigatohd02bg5hjg8mrdt82.apps.googleusercontent.com',
    iosBundleId: 'com.example.flappyBird',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-oOIWy_ZznXjeXQGZ7ByT4mOHGyeqgC4',
    appId: '1:808424067899:ios:76e8d418c16fe808079d1e',
    messagingSenderId: '808424067899',
    projectId: 'bookverse-8ac90',
    storageBucket: 'bookverse-8ac90.appspot.com',
    androidClientId: '808424067899-k8h5tg2rroov2srnmmo214uci1v28lml.apps.googleusercontent.com',
    iosClientId: '808424067899-vo3nf45oq3qd9etr87jhkh8qhdv57a5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookVerse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0tKaXVtfzlzeUHtdKukKIh8Doo3c1Wag',
    appId: '1:808424067899:web:00877372024f656d079d1e',
    messagingSenderId: '808424067899',
    projectId: 'bookverse-8ac90',
    authDomain: 'bookverse-8ac90.firebaseapp.com',
    storageBucket: 'bookverse-8ac90.appspot.com',
  );

}